import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const [screenSize, setScreenSize] = useState({
    width: 0,
    height: 0,
  });

  useEffect(() => {
    // Function to update screen size state
    const handleResize = () => {
      setScreenSize({
        width: window.innerWidth,
        height: window.innerHeight,
      });
    };

    // Set initial size
    handleResize();

    // Add event listener for resize
    window.addEventListener("resize", handleResize);

    // Clean up the event listener on component unmount
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  const router = useRouter();

  const handleStaffMenu = () => {
    router.push("./staff");
  };

  const handleBranchMenu = () =>{
    router.push("./branch")
  }

  const handleClientMenu = () =>{
    router.push("./client")
  }

  return (
    <>
      <Head>
        <title>Dream Home Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/House-logo.png" />
      </Head>
      <main
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          height: "100vh",
          backgroundColor: "white",
        }}
      >
        <div
          style={{
            position: "absolute",

          }}
        >
          <Image
            src="/main-page.jpg"
            style={{ opacity: 0.7,
                position:"sticky",
                top:0
             }}
             draggable="false"
             width= {screenSize.width * 0.8}
             height={screenSize.height} 
          />
        </div>

        <div
          style={{
            position: "absolute",
            justifyContent: "center",
            display: "flex",
            flexDirection: "row",
          }}
        >
          <button
            style={{
              width: 200,
              backgroundColor: "#2832c2",
              textAlign: "center",
              padding: 10,
              color: "white",
              borderTopLeftRadius:10,
              borderBottomLeftRadius:10,
              cursor: "pointer",
            }}
            onClick={handleStaffMenu}
          >
            <h3>Staff Main Menu</h3>
          </button>
          <button
            style={{
              width: 200,
              backgroundColor: "#2832c2",
              textAlign: "center",
              padding: 10,
              color: "white",
              cursor: "pointer",
            }}
            onClick={handleBranchMenu}

          >
            <h3>Branch Main Menu</h3>
          </button>
          <button
            style={{
              width: 200,
              backgroundColor: "#2832c2",
              textAlign: "center",
              padding: 10,
              borderTopRightRadius: 10,
              borderBottomRightRadius: 10,
              color: "white",
              cursor: "pointer",
            }}
            onClick={handleClientMenu}

          >
            <h3>Client Main Menu</h3>
          </button>
        </div>
      </main>
    </>
  );
}
